-- AlterTable
ALTER TABLE "product" ALTER COLUMN "discount" DROP NOT NULL,
ALTER COLUMN "stars" SET DEFAULT 0,
ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "user" ALTER COLUMN "rut" DROP NOT NULL,
ALTER COLUMN "phone" DROP NOT NULL,
ALTER COLUMN "date" DROP NOT NULL;
